### ISSUE TITLE
Won't compile under Fedora 40

### ISSUE THREAD

**Issue by FuzzyWuggzy** [FloFri/kwin-blishhud-shader#1]
Hi

I tried building building this under Fedora 40, but I'm getting errors related to kwineffects, here's the cmake log: 

[cmakelog.txt](https://github.com/user-attachments/files/16984887/cmakelog.txt)

Thank you for making this, it'll be a huge help once it's working.

Kind regards

F

**Comment by FloFri** [comment]
I just released a new version which might resolve the problem. Sadly I currently have no working Fedora installation available. Could you please try if this version works?

**Comment by FuzzyWuggzy** [comment]
Thank you so much for responding.

`kf6-kconfigwidgets-devel` and `kf6-kcmutils-devel` need to be added to the list of dependencies in the readme.

Cmake completes without issue but now make errors with a missing file named `kwinoffscreeneffect.h`, it was provided by `kwin-devel` in Fedora 39, but doesn't exist in the 40 repos. [makelog_noh.txt](https://github.com/user-attachments/files/17007082/makelog_noh.txt)

Figuring there was nothing to lose I downloaded the rpm of `kwin-devel`, extracted the .h files from it and included them in the cmakelist. make got to 100% then still error'ed out. [makelog_h.txt](https://github.com/user-attachments/files/17007096/makelog_h.txt)

Sorry I can't be of much help. Thank you again.

**Comment by 256shadesofgrey** [comment]
I get the same error on EndeavourOS (i.e. arch).

**Comment by FloFri** [comment]
Made some more changes to the handling of QT6. Have also fixed the needed packages for a Fedora build in the README (thx Fuzzy) and tested it with a VM.

Should build now.

**Comment by FloFri** [comment]
Should be fixed.

**Comment by FuzzyWuggzy** [comment]
Hello.

I'm so sorry it's so late, I typed a response then forgot to post it.

I'm also sorry posting this will reopen the issue, but I couldn't not say how grateful I am to you for fixing the issue, I've been using the effect for the past few weeks for map completion and can confirm it works amazingly. 

Thank you again. Take care.

F
