### ISSUE TITLE
Fedora 40 + QT6 weird

### ISSUE THREAD

**Issue by PenguinSSH** [FloFri/kwin-blishhud-shader#2]
Hey, 

I tried this out on Fedora 40 + KDE.  Window rules configured albeit removed opacity settings.  Blishhud seems to draw correctly and shaders seems to work properly since I don't see a blackscreen.  However, the rendering is weird here.

![image](https://github.com/user-attachments/assets/cd3af171-77e3-4bba-8da7-297dd68aed36)

I may be missing something here :|

**Comment by FloFri** [comment]
This might happen when you remove the oppacity settings. It has to be at 99% because else there are problems with redrawing.
Try adding the oppacity setting at 99%.

**Comment by PenguinSSH** [comment]
Quick on the reply he he.  Thanks for the input!  It does work 100%, this is genius!!
